language: R
sudo: false
cache: packages
env:
  - NODE_VERSION="4.0"
  - NODE_VERSION="4.1"
  - NODE_VERSION="4.2"
  - NODE_VERSION="5.4"
os: 
  -windows

after_success:
  - Rscript -e 'covr::codecov()'
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"
