language: R
sudo: false
cache: packages
os: 
  -osx
  -linux
after_success:
  - Rscript -e 'covr::codecov()'
env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"
