# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpparma_hello_world <- function() {
    .Call(`_sfpca_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_sfpca_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_sfpca_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_sfpca_rcpparma_bothproducts`, x)
}

sfpca <- function(X, Omega_u, Omega_v, alpha_u = 0, alpha_v = 0, lambda_u = 0, lambda_v = 0, P_u = "NotSupplied", P_v = "NotSupplied", EPS = 1e-4, MAX_ITER = 1e+3L) {
    .Call(`_sfpca_sfpca`, X, Omega_u, Omega_v, alpha_u, alpha_v, lambda_u, lambda_v, P_u, P_v, EPS, MAX_ITER)
}

